### PR TITLE
WIP Bug 23 fix2

### PR DESCRIPTION
**Pull request by twiecki**
Continuation of https://github.com/quantopian/empyrical/pull/25

### CODE REVIEW

**Comment by twiecki** [comment]
I think a constant array is a bad test-case for the factor_returns, I changed them to something else, can still think about that. But it does require the numbers in the tests to be adapted.

**Comment by jdricklefs** [comment]
@jbredeche 

Using the 1000-item random-noise series from the unit tests

```
In [6]: %timeit new_beta(noise, noise, 0.0)
1000 loops, best of 3: 1.09 ms per loop

In [8]: %timeit old_beta(noise, noise, 0.0)
1000 loops, best of 3: 1.02 ms per loop
```

Doesn't seem significantly different.

**Comment by jdricklefs** [comment]
> I think a constant array is a bad test-case for the factor_returns,

In Quantopian-terms, it seems possible that an algorithm could set their benchmark to a relatively illiquid security, resulting in some duration of constant returns? Is this something we should handle or is it an inherently broken scenario?

**Comment by jbredeche** [comment]
thanks @jdricklefs

**Pull request merged**
