### PR TITLE
TST: Change noop assertions to check for nan

### PR DESCRIPTION
**Pull request by richafrank**
(Everything is not equal to nan!)

### CODE REVIEW

**Comment by richafrank** [comment]
@twiecki I changed these assertions from being trivially true, since everything evaluates not equal to nan, and now one of them fails.  I'm not sure if the test or the risk function(s) should be changed.  What are your thoughts?

**Comment by richafrank** [comment]
Specifically, the test that fails is `test_alpha_beta_with_nan_inputs_0`.

**Comment by twiecki** [comment]
I think the problem is not the nans in the input here but instead the flat-line we pass in for benchmark. @ahgnaw can we replace all of those with non-flat lines? I'm not sure what relevant case we're testing there.

**Comment by ahgnaw** [comment]
The flat line here is  wrongly used as an input. The alpha and beta values of any return series against a flat line will return np.nan. In other tests, the flat line is used as a sanity check, e.g. `test_alpha_2`. Getting rid of all tests that use a flat line as a benchmark would remove some property tests.

**Comment by ahgnaw** [comment]
LGTM

**Comment by twiecki** [comment]
:+1:

**Pull request merged**
