### PR TITLE
Fix sortino_ratio downside_risk v2

### PR DESCRIPTION
**Pull request by lostAstronaut**
Reopen to fix annualization of downside risk in sortino_ratio after unittests have been fixed

### CODE REVIEW

**Comment by lostAstronaut** [comment]
Seems the tests still aren't passing.

**Comment by lostAstronaut** [comment]
I'll have some time tonight, I can check the tests

**Comment by lostAstronaut** [comment]
@twiecki tests are fixed to match the corrected ratio

**Comment by lostAstronaut** [comment]
@twiecki Any thoughts on updating this?

**Comment by twiecki** [comment]
@lostAstronaut Thanks for the fix!

**Comment by lostAstronaut** [comment]
@twiecki Any time! Glad to help

**Pull request merged**
