### PR TITLE
Fixed #61, annualization of Sortino Ratio

### LINKED ISSUE #61: Wrong annualization of Sortino Ratio?
The Sortino Ratio is annualized in stats.py as follows:
`return sortino * ann_factor`

where `ann_factor` is
`ann_factor = annualization_factor(period, annualization)`

I believe you actually meant to return
`return sortino * np.sqrt(ann_factor)`

just like you did with the Sharpe Ratio.

### PR DESCRIPTION
**Pull request by gabrieleiacono**

### CODE REVIEW

**Comment by twiecki** [comment]
LGTM, thanks!

**Comment by twiecki** [comment]
@gabrieleiacono We still need to adjust the unit-tests.

**Comment by rsheftel** [comment]
This pull request is not correct. Please see my comment on issue #61

**Comment by twiecki** [comment]
Closing in favor of #74. Thanks anyhow.

**Pull request closed without merging**
