### PR TITLE
Added Quarterly Return

### PR DESCRIPTION
**Pull request by cgdeboer**
Added another common periodicity (quarterly) to the aggregate returns function, along with some relevant tests.

### CODE REVIEW

**Comment by cgdeboer** [comment]
@twiecki or @gusgordon looks like some issues with dependencies on the python3+ builds. Shall I investigate and fix or is someone looking at this already ?

**Comment by twiecki** [comment]
Thanks @cgdeboer! Yes, if you can find the issue it would be much appreciated.

**Comment by cgdeboer** [comment]
@twiecki looks like the conda channel was pointing to a `quantopian` namespace that perhaps does not have all the correct versions in there. Updated the `.travis.yml` to point to the community managed **conda-forge** channel. Hope that's ok.

**Comment by cgdeboer** [comment]
@twiecki  can you offer some guidance about when and how often maintainers merge and push to pypi with this project ? Just trying to plan for an upcoming release.

**Comment by cgdeboer** [comment]
@gusgordon @richafrank @twiecki not sure what protocol is on this project. Can you give some insights on PR merging and release timing ?

**Comment by twiecki** [comment]
This looks great, thanks @cgdeboer!

**Pull request merged**
